language: c
os: linux
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - software-properties-common
      - libfuse-dev
      - linux-libc-dev
      - libc6-dev
      - libgcc-8-dev
      - g++
      - pkg-config
      - valgrind

before_install:
#  - pip install --user cpp-coveralls
  - |
    CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

script:
  - cmake -Bbuild -H.
  - cd build
  - make
  - mkdir fsRoot
  - ./naofs fsRoot -s
  - for file in ../test/bash_tests/*; do bash "$file"; done

#after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
