language: c
compiler: gcc
sudo: false # only for faster builds
dist: bionic
addons:
  apt:
    packages:
    - libfuse-dev
    - pkg-config
before_install:
  - pip install --user cpp-coveralls
script: make nao
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'