language: c
sudo: false
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libfuse-dev
      - linux-libc-dev
      - libc6-dev
      - libgcc-8-dev
      - pkg-config

before_install:
#  - pip install --user cpp-coveralls
  - mkdir fsRoot

script:
  - cmake -Bbuild -H.
  - cd build
  - make
  - mkdir fsRoot
  - ./naofs fsRoot -d -f -s

#after_success:
#  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
