#ifndef _DISK_METADATA_H
#define _DISK_METADATA_H

#define METABLOCKS 4

#define BOOT_BLOCK 0
#define SUPER_BLOCK 1
#define FREE_LIST_BLOCK 2
#define INODE_LIST_BLOCK 3
#define INODE_BLOCKS_HEAD 4

#endif
